services:
  - type: web
    name: lifelink-api
    env: docker
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: MONGODB_URI
        sync: false  
      - key: JWT_SECRET
        sync: false
      - key: JWT_ACCESS_EXPIRATION
        value: 3600000
      - key: JWT_REFRESH_EXPIRATION
        value: 86400000