spring:
  application:
    name: LikeLink
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: lifelink 
      auto-index-creation: true

server:
  port: ${PORT:10000}  

jwt:
  secret: ${JWT_SECRET}
  accessToken:
    expiration: ${JWT_ACCESS_EXPIRATION:3600000}
  refreshToken:
    expiration: ${JWT_REFRESH_EXPIRATION:86400000}